### ISSUE TITLE
Running the pipe operator

### ISSUE THREAD

**Issue by br3akzero** [maxchuquimia/cockle#1]
First of love how you used `dynamicMemberLookup ` and `dynamicCallable ` to create Cockle (the name doesn't do it justice 😅). I was wondering how can I handle something as the `|` pipe operator using Cockle. 

For example: 
```
# Unix command
ls -al | grep .git 
```

```
import Cockle

let shell = try Shell() 

let lsOutput = shell.ls(_al: ())
let grepOutput = … 
```

This might not be an issue but more of a question on how to use commands such as `awk` and `grep` with Cockle.

**Comment by maxchuquimia** [comment]
Hi @rashadatjou, sorry for the late response! I haven't thought much about the pipe operator for this project… the idea was more to allow command usage natively rather than bridging all behaviour and trying to rewrite how the shell works 😉 

I would imagine there's a way to pass the FileHandle output of one command to the input of another -- you're welcome to give it a go!
